# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WittyFilter
description: > # this means to ignore newlines until "baseurl:"
   这个人很懒，什么都没写
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wittyfilter.github.io" # the base hostname & protocol for your site
tagline:	'并不机智的滤波器'
paginate:	5

# About/contact
author:
  name:              Simon Yang
  url:               https://twitter.com/WittyFilter
  email:             

# Custom vars
version:             2.0.0

gems: [jekyll-paginate]

# Build settings
markdown: kramdown

permalink: "/blog/:title"

flickr:
  screen_name: wittyfilter
  api_key: 3071e8d508c99f6debb6cefc0d789a51
  api_secret: 52656154d66916cd

# 'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
