# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WittyFilter
email: 
description: > # this means to ignore newlines until "baseurl:"
   这个人很懒，什么都没写
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wittyfilter.github.io" # the base hostname & protocol for your site
twitter_username: WittyFilter
github_username:  wittyfilter

# Build settings
markdown: kramdown

permalink: "/blog/:title"

flickr:
  screen_name: wittyfilter
  api_key: 3071e8d508c99f6debb6cefc0d789a51
  api_secret: 52656154d66916cd

flickr_set:
  gallery_tag:   'p'
  gallery_class: 'album'
  a_href:        nil
  a_target:      '_blank'
  image_rel:     ''
  image_size:    's'
  api_key:       '3071e8d508c99f6debb6cefc0d789a51'
