# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

excerpt_separator: <!-- more -->


title: WittyFilter
description: > # this means to ignore newlines until "baseurl:"
 幻想乡音乐家与摄影师
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wittyfilter.github.io" # the base hostname & protocol for your site
tagline:	'机智的滤波器'

timezone: Asia/Shanghai

paginate: 4
paginate_path: "/page:num/"

# About/contact
author:
  name:              Zhe Yang
  url:               https://www.instagram.com/wittyfilter/
  email:             

# Custom vars
version:             4.0.0


# Build settings
markdown: kramdown

permalink: "/blog/:title"

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-admin


