# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WittyBlog
email: 
description: > # this means to ignore newlines until "baseurl:"
   这个人很懒，什么都没写
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wittyfilter.github.io" # the base hostname & protocol for your site
twitter_username: WittyFilter
github_username:  wittyfilter

# Build settings
markdown: kramdown
